### ISSUE TITLE
Support for Alfresco 5.1

### ISSUE THREAD

**Issue by angelborroy-ks** [jottley/alfresco-maxversion-policy#4]
The addon seems to work for Alfresco 5.1 releases without changes.

I've been testing it in order to support a colleague: https://community.alfresco.com/thread/214763-keep-only-n-versions-of-document

Can be `module.properties` updated to produce a new release of the addon?

**Comment by jottley** [comment]
Yes we can do that

**Comment by jottley** [comment]
Version 0.0.9 adds support for 5.1
