### ISSUE TITLE
Need help to make work

### ISSUE THREAD

**Issue by Blazer34** [jottley/alfresco-maxversion-policy#7]
Hello there, first off, tks for the work in this file.

I need help to make work, i follow the instructions, stop my alfresco server, copied the file to amps_share, and execute the command  `./apply_amps.sh`, but, the version system still working as default, it's not limited to 10 (as default in the amp) i try to setup a diferent number in the alfresco-global.properties file, but, still no sucess... everything look's fine, but it's not working. Im using Alfresco CE 6.0.2.1

im i doing something wrong? Any help are much, much welcome, tks! 

PS.: This my test server, not in production
PS2.: Apologize for my english.

![alfresco_problem](https://user-images.githubusercontent.com/46167978/62482641-12c95680-b78c-11e9-959b-54b7bbf7dbce.png)

![alfresco_problem_2](https://user-images.githubusercontent.com/46167978/62482921-dfd39280-b78c-11e9-9c68-4d3bbb4f556f.png)

![alfresco_problem_3](https://user-images.githubusercontent.com/46167978/62484125-dbf53f80-b78f-11e9-8630-da84047a649c.png)

My alfresco-global.properties
`
###############################
###############################

dir.root=/opt/alfresco/alf_data

alfresco.context=alfresco
alfresco.host=127.0.0.1
alfresco.port=8080
alfresco.protocol=http

share.context=share
share.host=127.0.0.1
share.port=8080
share.protocol=http

### database connection properties ###
db.driver=org.postgresql.Driver
db.username=alfresco
db.password=
db.name=alfresco
db.url=jdbc:postgresql://localhost:5432/${db.name}
# Note: your database must also be able to accept at least this many connections.  Please see your database documentation for instructions on how to configure this.
db.pool.max=275
db.pool.validate.query=SELECT 1

# The server mode. Set value here
# UNKNOWN | TEST | BACKUP | PRODUCTION
system.serverMode=UNKNOWN

### FTP Server Configuration ###
ftp.port=21

### RMI registry port for JMX ###
alfresco.rmi.services.port=50500

### External executable locations ###
ooo.exe=/opt/alfresco/libreoffice/program/soffice.bin
ooo.enabled=true
ooo.port=8100
img.root=/opt/alfresco/common
img.dyn=${img.root}/lib
img.exe=${img.root}/bin/convert
alfresco-pdf-renderer.root=/opt/alfresco/common/alfresco-pdf-renderer
alfresco-pdf-renderer.exe=${alfresco-pdf-renderer.root}/alfresco-pdf-renderer

jodconverter.enabled=false
jodconverter.officeHome=/opt/alfresco/libreoffice
jodconverter.portNumbers=8100

### Initial admin password ###
alfresco_user_store.adminpassword=

### E-mail site invitation setting ###
notification.email.siteinvite=false

### License location ###
dir.license.external=/opt/alfresco

### Solr indexing ###
index.subsystem.name=solr4
dir.keystore=${dir.root}/keystore
solr.host=localhost
solr.port.ssl=8443

### Allow extended ResultSet processing
security.anyDenyDenies=false

### Smart Folders Config Properties ###
smart.folders.enabled=false

### Remote JMX (Default: disabled) ###
alfresco.jmx.connector.enabled=false

##################################################
#Version limiter                                 #
##################################################
maxVersions=8

**Comment by jottley** [comment]
@Blazer34 Let me run some tests to make sure that it is working as expected on 6.x.

**Comment by Blazer34** [comment]
@jottley Awesome, ok!, thank you very much in advance!

**Comment by douglascrp** [comment]
@jottley he has installed the amp into share.war, not alfresco.war

I noticed that by the shared image.

**Comment by jottley** [comment]
@douglascrp Good catch!  @Blazer34 As Douglas stated above, you'll need to install the amp into the alfresco.war file not the share.war file.  That should fix your issue.

**Comment by Blazer34** [comment]
Hello there!

Sorry for my ignorance, but how do i install on alfresco.war? When running the apply_amps.sh command it automatically installs to /opt/alfresco/tomcat/webapps/share.war

**Comment by jottley** [comment]
@Blazer34 What directory are you placing the amp in?  There are normally two directories amps and amps_share.  It should go in the amps directory.

**Comment by Blazer34** [comment]
@jottley Hello! First, thank you very much for the help.

 i've placed the .amp in /opt/<my_alfresco_installation>/alfresco/amps and tried to install using the ./apply_amps, still, the path of instalation is automatically set to the share.war not alfresco.war
![alf](https://user-images.githubusercontent.com/46167978/62985129-43546480-be0c-11e9-8b57-29a225726bc4.jpg)

I'm current reading about using the MMT (Module Management Tool) to install the amp, but, didn't go to good so far.

PS.: i've install a libreOffice amp and works fine, but, i've placed in amps_share and the installation is on share.war, don't know if this info is important, but it's here anyway,

**Comment by jottley** [comment]
@Blazer34 Hopefully there is not a bug a bug in the apply_amps script. (Just to make sure...you removed the amp from the amps_share directory...)

Can you post a link to the apply_amps.sh in a gist here so I can take a look at it?

**Comment by Blazer34** [comment]
Hello @jottley 

Well, since this alfresco server was a test server, i've made a clean reinstall e try to apply the amp and work's! 
My problem was:
At first, i've put the .amp in amps_share and install (did not work) them, after talk to you and the tip of @douglascrp, i put the amp in the amps folder and run the apply amps command again, still not work because the amp was already installed in the share.war. i try to uninstall, but without sucess (i'm reading more about how to uninstall correctly), so, i made a clean installation, put the amp in place and know its fine.

Thank you very much to you and @douglascrp for the help. Gonna keep reading and learning more. tks!

**Comment by jottley** [comment]
@Blazer34 Glad to hear it is working now!
